server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database01?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /mystatic/** #所有以host:port/mystatic/ 开头的请求都将被当成静态资源请求，在对应的resources/static/中查找
    #例如 /【mystatic/css/index_html.css】 对应的文件在服务器的位置为 /resources/static/【css/index_html.css】


  thymeleaf:
    #下面两个内容对应的是，Controller方法的返回值为字符串时，比如login，2
    #那么springboot给这个字符串包装成：classpath:/templates/login.html,然后加载对应位置的文件。
    prefix: classpath:/templates/
    suffix: .html
